blank_issues_enabled: true
contact_links:
  - name: ğŸŒ Website
    url: https://lagbase.com
    about: Visit lagbase.com for more information
  - name: ğŸ’¬ General Questions
    url: mailto:hello@lagbase.com
    about: For questions not related to bugs or features
  - name: ğŸ¦ Twitter
    url: https://x.com/lagaboratory
    about: Follow us for updates
